### ISSUE TITLE
Web-based copytrade Project

### ISSUE THREAD

**Issue by aldyanimayazar** [Reiryoku-Technologies/cTrader-Layer#1]
Hi I just want to develop project with this library. Just wondering if we are able to create new order and copytrade from IC market or other brokers using this library. The goal is to clone/copy the exact amount trade (close/open/StopLoss/etc) from the web-based dashboard. May i know how I can achieve this using Typescript/NestJs ? Thank you.

**Comment by Vasile-Peste** [comment]
Yes, you can do all the things that you have mentioned. However you need a discrete programming ability. Everything is described at https://openapi.ctrader.com. So basically, if you follow the documentation, you can create your project step by step.
